{
  super(message);
  ExceptionUtils.initCause(this,cause);
}
