{
  this.exception=exception;
  initCause(exception);
}
